export const UPDATE_PROFILE_STATE = 'UPDATE_PROFILE_STATE';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const ADD_MY_ITEM = 'ADD_MY_ITEM';
export const DELETE_MY_ITEM = 'DELETE_MY_ITEM';
export const UPDATE_MYITEMS_STATE = 'UPDATE_MYITEMS_STATE';
export const UPDATE_ALLITEMS_STATE = 'UPDATE_ALLITEMS_STATE';
